# Generated by Django 3.2.12 on 2022-03-29 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockCenterLine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='query_count',
            field=models.IntegerField(verbose_name='계산횟수'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='setting',
            name='max_value',
            field=models.IntegerField(verbose_name='최대값'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='min_value',
            field=models.IntegerField(verbose_name='최소값'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='selected',
            field=models.JSONField(verbose_name='선택여부'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='unit',
            field=models.IntegerField(verbose_name='단위'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='setting',
            name='weight',
            field=models.FloatField(verbose_name='가중치'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
