# Generated by Django 3.2.12 on 2022-03-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCenterLine', '0005_alter_setting_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='setting_count',
            field=models.IntegerField(default=0, verbose_name='환경저장횟수'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='query_count',
            field=models.IntegerField(default=0, verbose_name='계산횟수'),
        ),
    ]
